### PR TITLE
Fix small UI issues

### LINKED ISSUE #666: Small UI fixes
Requested by @cloudhead.

image
image (1)

Files without content don't have a placeholder.
Screenshot 2023-04-04 at 17 12 26

### PR DESCRIPTION
**Pull request by sebastinez**
This PR closes #666, #669, #670

See commits for changeset

## Adjust commit view CSS
image

## Show blockies in PeerSelector
Bildschirmfoto 2023-04-13 um 21 47 34
Bildschirmfoto 2023-04-13 um 21 46 12
I also removed the fork icon once a peer is selected, I don't think it helps and it doesn't look good together with the blockie

## New patch and issue teasers
- Reduced formatted object ids to 7 instead of 11 digits
Bildschirmfoto 2023-04-13 um 21 49 00

## Improved subtitles and removed soft line breaks
Bildschirmfoto 2023-04-13 um 21 49 53

## Reduced code font to `--font-size-small`
Bildschirmfoto 2023-04-13 um 21 50 49

## Added placeholder for empty file
Bildschirmfoto 2023-04-13 um 21 52 43

### CODE REVIEW

File: src/views/projects/PeerSelector.svelte [hunk 1]
```diff
@@ -105,6 +116,17 @@
     <Dropdown
       {items}
       selected={peer}
-      on:select={e => switchPeer(e.detail.value)} />
+      on:select={e => switchPeer(e.detail.value)}>
+      <div class="peer-item" slot="item" let:item>
+        <Avatar nodeId={item.value} inline />
+        <!-- We ignore prettier here for the following line
+             to avoid getting a whitespace between did:key: and the nid due to a newline -->
+        <!-- prettier-ignore -->
```
Comment (rudolfs) [inline src/views/projects/PeerSelector.svelte:124]: Nice one, wish I had thought of this earlier.

**Review by rudolfs — COMMENTED** [review]
The peer selector could use a bit more padding to the left and right when a peer is selected.

Screenshot 2023-04-14 at 14 21 38

Otherwise LGTM. 👓
