### PR TITLE
Fix relative markdown file links

### LINKED ISSUE #682: Relative markdown links don't work
Eg. a link like [README](README.md) links to the wrong place.

See here links in readme here: https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5

### PR DESCRIPTION
**Pull request by sebastinez**
This PR should close #682, #645

It adds a `.file-link` class to eventual relative file links inside markdowns that also aren't hash anchor links.
Then we are able in the `Markdown` component to query those elements and call `updateProjectRoute` with the new path

This is something I would like to write a e2e test about.. But I'll wait for CLI tooling, since it needs changes to the seed fixture and I think that can wait.

### CODE REVIEW

File: src/components/Markdown.svelte [hunk 1]
```diff
@@ -30,6 +32,21 @@
     // eslint-disable-next-line @typescript-eslint/naming-convention
     dompurify.sanitize(marked.parse(content), { SANITIZE_DOM: false });
 
+  function handleMarkdownFileLinkNavigation(event: any) {
+    if (event.target.matches(".file-link")) {
+      event.preventDefault();
+      const route = get(activeRouteStore);
```
Comment (rudolfs) [inline src/components/Markdown.svelte:38]: We can just use Svelte syntax here:
```diff
diff --git a/src/components/Markdown.svelte b/src/components/Markdown.svelte
index a8ba36c5..81c54171 100644
--- a/src/components/Markdown.svelte
+++ b/src/components/Markdown.svelte
@@ -3,7 +3,6 @@
   import matter from "@radicle/gray-matter";
   import { marked } from "marked";
   import { onMount } from "svelte";
-  import { get } from "svelte/store";
   import { toDom } from "hast-util-to-dom";

   import * as utils from "@app/lib/utils";
@@ -35,7 +34,7 @@
   function handleMarkdownFileLinkNavigation(event: any) {
     if (event.target.matches(".file-link")) {
       event.preventDefault();
-      const route = get(activeRouteStore);
+      const route = $activeRouteStore;
       if (route.resource === "projects") {
         updateProjectRoute({
           path: utils.canonicalize(
```

Comment (sebastinez) [reply src/components/Markdown.svelte:38]: Ah you're right, good catch 👍

File: src/components/Markdown.svelte [hunk 2]
```diff
@@ -79,6 +101,15 @@
     }
 
     await Promise.allSettled(treeChanges);
+
+    return () => {
```
Comment (rudolfs) [inline src/components/Markdown.svelte:105]: I think we don't need to clean up anything here, because it wouldn't work on an `async` function anyway:

> This behaviour will only work when the function passed to onMount synchronously returns a value. async functions always return a Promise, and as such cannot synchronously return a function.

and there wouldn't be anything to click on when the component is destroyed, so I think any click handlers would be cleaned up automatically.

File: src/components/Markdown.svelte [hunk 3]
```diff
@@ -30,6 +32,21 @@
     // eslint-disable-next-line @typescript-eslint/naming-convention
     dompurify.sanitize(marked.parse(content), { SANITIZE_DOM: false });
 
+  function handleMarkdownFileLinkNavigation(event: any) {
```
Comment (rudolfs) [inline src/components/Markdown.svelte:35]: I prefer it when we callback name is describing the action, so in this case it would be `navigateToMarkdownLink`.

File: src/components/Markdown.svelte (hunk 2 above)
Comment (sebastinez) [reply src/components/Markdown.svelte:105]: Yeah you're right!

**Review by rudolfs — APPROVED** [review]
