### PR TITLE
Remove WalletConnect compatible link

### LINKED ISSUE #299: Fix broken compatible WalletConnect wallets
And again it seems that the link to a compatible wallet listing for WalletConnect is broken.

The latest working link it seems is: https://explorer.walletconnect.com/registry?type=wallet

This edit should be made here: https://github.com/radicle-dev/radicle-interface/blob/cbbaadd3307bba182e8cc88a3a1279b0a42825f5/src/components/Modal/ConnectWallet.svelte#L56

### PR DESCRIPTION
**Pull request by sebastinez**
- Removes WalletConnect-compatible wallet link, which is not reliable.
- Adds a generic text to let people know, they should use a WalletConnect-compatible wallet.

Closes #299

### CODE REVIEW

File: src/components/Modal/ConnectWallet.svelte [hunk 1]
```diff
@@ -52,10 +52,7 @@
 
     <div slot="subtitle">
       <div class="text-small">
-        WalletConnect<br/>
-        <a href="https://walletconnect.com/registry?type=wallet" class="link">
-          View compatible wallets
-        </a>
+      Scan QR code with a <br />WalletConnect-compatible wallet
```
Comment (cloudhead) [inline src/components/Modal/ConnectWallet.svelte:55]: Can we just leave this as `WalletConnect` like before and remove the link?

Comment (sebastinez) [reply src/components/Modal/ConnectWallet.svelte:55]: Yeah sure 👍

Comment (sebastinez) [reply src/components/Modal/ConnectWallet.svelte:55]: It seemed that `WalletConnect` by itself, was standing pretty alone so I thought an explanation was maybe better than to just show `WalletConnect`. 

Or maybe we could change the `Connect your wallet` to something alluding to `WalletConnect`?
Maybe `Connect with WalletConnect`?

Comment (sebastinez) [reply src/components/Modal/ConnectWallet.svelte:55]: Maybe even better we could do a listing of different wallets, similar to Workstreams
Bildschirmfoto 2022-08-12 um 14 33 57

The Metamask button would be like clicking on `Connect with Metamask` and when clicking on WalletConnect, we could implement into our own style, the WalletConnect QR Modal to allow connection with deep linking on mobile ref #287

Would probably need some rework on how we manage the wallet connect state inside the app

wdyt @cloudhead

Comment (cloudhead) [reply src/components/Modal/ConnectWallet.svelte:55]: Two clicks vs. 1

Comment (sebastinez) [reply src/components/Modal/ConnectWallet.svelte:55]: > Two clicks vs. 1

Okay 👌
